name: SwiftMacrosExample

options:
  bundleIdPrefix: com.github.shnhrrsn.swift-macros-xcodegen

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  SampleApp:
    type: application
    platform: [macOS, iOS]
    scheme: {}
    sources:
      - path: Sources/SampleApp
    dependencies:
      - target: SampleMacros_${platform}
    settings:
      CODE_SIGN_IDENTITY: "-"
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: 1.0
      MARKETING_VERSION: 1.0
      OTHER_SWIFT_FLAGS: "$(inherited) -Xfrontend -load-plugin-library -Xfrontend ${BUILD_DIR}/${CONFIGURATION}/libSampleMacrosPlugin.dylib" # This line needs to be in any target that uses the macros

  SampleMacros:
    type: library.dynamic
    platform: [macOS, iOS]
    scheme: {}
    sources:
      - path: Sources/SampleMacros
    dependencies:
      - target: SampleMacrosPlugin
        link: false # Dependency on the plugin so it builds, but do not link against it or bundle it
        embed: false
    settings:
      OTHER_SWIFT_FLAGS: "$(inherited) -Xfrontend -load-plugin-library -Xfrontend ${BUILD_DIR}/${CONFIGURATION}/libSampleMacrosPlugin.dylib" # This line needs to be in any target that uses the macros

  SampleMacrosPlugin:
    type: library.dynamic
    platform: macOS # <-- Important, plugins are only on macOS since they run during compile time on the host
    sources:
      - path: Sources/SampleMacrosPlugin
    settings:
      SKIP_INSTALL: YES
      EXECUTABLE_PREFIX: lib
      CLANG_ENABLE_MODULES: YES
      SWIFT_INCLUDE_PATHS: "$(TOOLCHAIN_DIR)/usr/lib/swift/host"
      LIBRARY_SEARCH_PATHS: "$(TOOLCHAIN_DIR)/usr/lib/swift/host"
      DYLIB_COMPATIBILITY_VERSION: 1
      DYLIB_CURRENT_VERSION: 1
      LD_RUNPATH_SEARCH_PATHS: "$(TOOLCHAIN_DIR)/usr/lib/swift/host"
